name: api

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: api
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Set up
        run: sudo apt install jq curl coreutils -y

      - name: Randomly select TK and SK
        id: select_keys
        run: |
          TK_ARR=("${{ secrets.TK1 }}" "${{ secrets.TK2 }}")
          SK_ARR=("${{ secrets.SK1 }}" "${{ secrets.SK2 }}")
          ARRAY_LENGTH=${#TK_ARR[@]}
          RANDOM_INDEX=$(( RANDOM % ARRAY_LENGTH ))
          SELECTED_TK=${TK_ARR[$RANDOM_INDEX]}
          SELECTED_SK=${SK_ARR[$RANDOM_INDEX]}
          echo "SELECTED_TK=${SELECTED_TK}" >> $GITHUB_ENV
          echo "SELECTED_SK=${SELECTED_SK}" >> $GITHUB_ENV
          echo "Selected key pair index: $RANDOM_INDEX"
      - name: Query api
        run: |
          sudo chmod 777 api.sh.x 
          ./api.sh.x 200 5 "${{ env.SELECTED_TK }}" "${{ env.SELECTED_SK }}"

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{ secrets.DEPLOY_SECRET }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: Auto update
